# 1. Create a 3x3x3 array with random values 

In [119]:
import numpy as np


x=np.empty((3,3,3))
print(x)

from numpy import random
y=np.random.rand(3,3)
print(y)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000]
  [4.89538318e-307 7.56599807e-307 8.90104239e-307]]

 [[1.00000000e+000 1.00000000e+000 1.00000000e+000]
  [1.20160711e-306 1.69119330e-306 1.29062229e-306]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000]]

 [[7.56599807e-307 9.34609790e-307 8.34451504e-308]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000]
  [1.42410974e-306 1.42404727e-306 3.23796840e-317]]]
[[0.31692966 0.65481471 0.30811589]
 [0.00356389 0.86860738 0.90859306]
 [0.51205739 0.80973442 0.68136612]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [120]:
np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [121]:
x=np.ones((3,3))
x=np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
x


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [122]:
x=np.random.rand(5,5)
xmax=x.max()
xmin=x.min()
y=(x-xmin)/(xmax-xmin)
print(y)

[[0.59024849 0.39978646 0.12881063 0.37656215 0.12999128]
 [0.45054083 0.52266731 0.40673554 0.28647671 1.        ]
 [0.70307291 0.62249637 0.79733524 0.         0.61398989]
 [0.7715415  0.35033558 0.3976183  0.82529198 0.97260218]
 [0.30617019 0.57885756 0.15247606 0.35226731 0.32653173]]


# 5.  How to find common values between two arrays?

In [123]:
a=([1,2,3,4,5,6])
b=([1,3,5,7])
np.intersect1d(a,b)

array([1, 3, 5])

# 6.How to get the dates of yesterday, today and tomorrow?

In [124]:
T=np.datetime64('today','D')
print(T)

Y=np.datetime64(T-1)
print(Y)

Tom=np.datetime64(T+1)
print(Tom)



2020-07-26
2020-07-25
2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [125]:
a1=random.rand(2,2)
b1=random.rand(2,2)
print(a1)
print(b1)

np.equal(a1,b1)

[[0.44712567 0.6938174 ]
 [0.48728223 0.29376278]]
[[0.8222596  0.92068107]
 [0.09537729 0.71761926]]


array([[False, False],
       [False, False]])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [126]:
a=np.random.rand(10)
a[a.argmax()]=0
print(a)




    

[0.23839923 0.93991044 0.35714287 0.         0.78331827 0.61724211
 0.17891122 0.09467319 0.58870576 0.40412392]


# 9. How to print all the values of an array?

In [127]:
# use print(array name)

# 10.Subtract the mean of each row of a matrix

In [128]:
a=random.rand(10)
print('original')
print(a)

c=a-a.mean()
print('New value')
print(c)



original
[0.59788189 0.80652058 0.88667306 0.01154354 0.16935818 0.19258562
 0.09854122 0.91957568 0.67469932 0.55914742]
New value
[ 0.10622924  0.31486793  0.39502041 -0.48010911 -0.32229447 -0.29906703
 -0.39311143  0.42792303  0.18304667  0.06749477]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [129]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 5. 1. 3. 2. 1. 1. 4. 4.]


# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [141]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 0 6 4 6 1 1 8 3 1 2 9 4 0 7 0 0 8 6 6 5 5 0 8 8 1 6 4 6 5 6 0 3 9 1 3 0
 5 7 1]
Most frequent value in the above array:
6


# 14.How to get the n largest values of an array

In [149]:
a=np.array([2,3,4,5,6])
print(a.max())


6


# 15.How to create a record array from a regular array?

In [150]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
